### PR TITLE
Added multi surface support

### PR DESCRIPTION
**Pull request by Subject-314159**
By adding global.surfaces[surface_index] each surface can now have their own streak.

### CODE REVIEW

**Comment by i-make-robots** [comment]
I think the way to deal with no-surface is the same as all-night worlds : use nauvis default.  I mean, how would time be kept in space?

**Comment by Subject-314159** [comment]
Not sure if you want to keep the announcements, mods that like to add surfaces like to add _a lot_ of surfaces and the console chat gets flooded quite quickly

**Comment by i-make-robots** [comment]
Is there a chance you can submit such that it doesn't report every line changed because of formatting?  It's really hard to tell what really changed.

Thank you!

**Comment by i-make-robots** [comment]
I'm still testing things, there's some conflict between the original and this PR, it can't find the surfaces table.  I had no idea the players could stand on many surfaces at once...

**Comment by Subject-314159** [comment]
Probably because the version wasn't changed in info.json and the save you test with already had this mod loaded. Since there is no configuration change the `script.on_configuration_changed` doesn't fire

Regarding formatting: Tried to re-commit but my git skills are insufficient and I'm not sure this actually solved the problem, any suggestions?

**Comment by i-make-robots** [comment]
I think what you've done is excellent and solves multiple things I wasn't sure about (first Factorio mod).

Awesome work!

**Comment by Subject-314159** [comment]
One more thing I just realized, in the `on_tick` there's being checked with only `if surface always_day then`, however I think with this setting the day still "progresses" in the background, perhaps it should be `if surface.always_day or surface.freeze_daytime then` (or only freeze_daytime)

**Comment by i-make-robots** [comment]
What's the difference between freeze_daytime and always_day?  it can freeze_daytime at night?

**Comment by Subject-314159** [comment]
Always_day is only a graphical change to the UI so that it doesn't get dark, but surface.daytime still changes according to surface.ticks_per_day, whereas freeze_daytime doesn't progress the surface.daytime

**Pull request merged**
